/*
 * Copyright (c) 2017-2018 Daniel Saukel
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package io.github.dre2n.factionsxl.config;

import de.erethon.commons.chat.MessageUtil;
import de.erethon.commons.config.Message;
import io.github.dre2n.factionsxl.FactionsXL;
import org.bukkit.ChatColor;
import org.bukkit.configuration.file.FileConfiguration;
import org.bukkit.configuration.file.YamlConfiguration;

/**
 * An enumeration of all messages.
 * The values are fetched from the language file.
 *
 * @author Daniel Saukel
 */
public enum FMessage implements Message {

    BULL_ID("bull.id", "&7Bull"),
    BULL_RIGHT_KLICK("bull.rightClick", "&2Right click to use"),
    CHAT_CHANNEL_SWITCHED("chat.channelSwitched", "&aYour chat channel has been switched to &v1&a."),
    CHAT_PREFIX_ADMIN("chat.prefix.admin", "**"),
    CHAT_PREFIX_MEMBER("chat.prefix.member", new String()),
    CHAT_PREFIX_MOD("chat.prefix.mod", "*"),
    CMD_ADD_CASUS_BELLI_SUCCESS("cmd.addCasusBelli.success", "&aSuccessfully added a &6&v1 &acasus belli against &v2 &afor &v3&a."),
    CMD_ADMIN_SUCCESS("cmd.admin.success", "&v1 &agave &v2 &athe leadership of &v3&a."),
    CMD_CASUS_BELLI_HEAD("cmd.casusBelli.head", "&aTarget &4| &aType &4| &aExpiration"),
    CMD_CASUS_BELLI_NO_EXPIRATION("cmd.casusBelli.noExpiration", "No expiration"),
    CMD_CLAIM_SUCCESS("cmd.claim.success", "&aSuccessfully annexed the region &v1&a."),
    CMD_CREATE_SUCCESS("cmd.create.success", "&v1 &acreated the new faction &v2&a."),
    CMD_CREATE_BULL_SUCCESS("cmd.createBull.success", "&aSuccessfully created the new bull &6&v1&a."),
    CMD_DESC_SUCCESS("cmd.desc.success", "&aThe faction &v1&a changed their description to: &6&v2&a."),
    CMD_DISBAND_SUCCESS("cmd.disband.success", "&v1 &adisbanded the faction &v2&a."),
    CMD_GIVE_REGION_SUCCESS("cmd.giveRegion.success", "&v1 &agave the region &v2 &ato &v3&a."),
    CMD_INVITE_FAIL("cmd.invite.fail", "&4Could change the invitation status of &v1&4."),
    CMD_INVITE_SUCCESS("cmd.invite.success", "&v1 &ainvited &v2 &ato join your faction."),
    CMD_KICK_FAIL("cmd.kick.fail", "&4You are not allowed to kick &v1&4."),
    CMD_KICK_SUCCESS("cmd.kick.success", "&v1 &akicked &v2 &aout of the faction."),
    CMD_LIST_TITLE("cmd.list.title", "&6&l= List of Factions ="),
    CMD_MAIN_WELCOME("cmd.main.welcome", "&aWelcome to &4Factions&fXL"),
    CMD_MAIN_HELP("cmd.main.help", "&aType in &o/f help&r&a for further information."),
    CMD_MOD_PROMOTE("cmd.mod.promote", "&v1 &apromoted &v2&a. He will now serve as a moderator."),
    CMD_MOD_DEMOTE("cmd.mod.demote", "&v1 &ademoted &v2&a. He will not serve as a moderator any longer."),
    CMD_MONEY_BALANCE("cmd.money.balance", "&aThe faction &v1 &ahas &6&v2&a."),
    CMD_MONEY_DEPOSIT_FAIL("cmd.money.deposit.fail", "&4You do not have enough money."),
    CMD_MONEY_DEPOSIT_SUCCESS("cmd.money.deposit.success", "&v1 &agave &6&v2 &ato the bank of &v3&a."),
    CMD_MONEY_WITHDRAW_FAIL("cmd.money.withdraw.fail", "&v1 &4cannot afford &6&v2..."),
    CMD_MONEY_WITHDRAW_SUCCESS("cmd.money.withdraw.success", "&v1 &atook &6&v2 &afrom the bank of &v3&a."),
    CMD_OPEN_CLOSED("cmd.open.closed", "&v1 &aclosed the faction for uninvited players."),
    CMD_OPEN_OPENED("cmd.open.opened", "&v1 &aopened the faction for uninvited players."),
    CMD_POWER("cmd.power", "&aThe player &v1 &ahas &6&v2 &apower points."),
    CMD_REGION_CLAIMS("cmd.region.claims", "&6Claims: "),
    CMD_REGION_CORES("cmd.region.cores", "&6Cores: "),
    CMD_REGION_OWNER("cmd.region.owner", "&6Owner: "),
    CMD_REGION_POPULATION("cmd.region.population", "&6Population: "),
    CMD_REGION_PRICE("cmd.region.price", "&6Price: "),
    CMD_REGION_TYPE("cmd.region.type", "&6Type: "),
    CMD_RELOAD_DONE("cmd.reload.done", "&aSuccessfully reloaded FactionsXL."),
    CMD_SET_ANTHEM_SUCCESS("cmd.setAnthem.success", "&v1 &aset the national anthem of &v2 &ato &6&v3&a."),
    CMD_SET_BANNER_SUCCESS("cmd.setBanner.success", "&v1 &adecided to let a new flag decorate the towers of &v2&a."),
    CMD_SET_CAPITAL_SUCCESS("cmd.setCapital.success", "&v1 &aset their capital to &v2&a."),
    CMD_SET_COLOR_SUCCESS("cmd.setColor.success", "&v1 &aset the livemap color of your faction to &6&v2 &a/ &6&v3&a. The icon is &6&v3&a."),
    CMD_SET_GOVERNMENT_SUCCESS("cmd.setGovernment.success", "&v1 &aset their government type to &6&v2&a."),
    CMD_SET_HOME_CHAR_FAIL("cmd.setHome.char.fail", "&6Your home location must be in allied or neutral territory."),
    CMD_SET_HOME_CHAR_SUCCESS("cmd.setHome.char.success", "&6You have successfully set your home location to this location."),
    CMD_SET_HOME_FACTION_FAIL("cmd.setHome.faction.fail", "&4The home location must be in the territory of the respective faction."),
    CMD_SET_HOME_FACTION_SUCCESS("cmd.setHome.faction.success", "&v1 &ahas set your faction home to a new position."),
    CMD_SET_POWER_SENDER("cmd.setPower.sender", "&aYou successfully set the power of &v1 &ato &6&v2&a."),
    CMD_SET_POWER_TARGET("cmd.setPower.target", "&v1 &aset your power &ato &6&v2&a."),
    CMD_SHOW_BALANCE("cmd.show.balance", "&6Balance: "),
    CMD_SHOW_CAPITAL("cmd.show.capital", "&6Capital: "),
    CMD_SHOW_DESCRIPTION("cmd.show.description", "&6Description: "),
    CMD_SHOW_FORMER_LEADERS("cmd.show.formerLeaders", "&6Former leaders: "),
    CMD_SHOW_GOVERNMENT_TYPE("cmd.show.governmentType", "&6Type of government: "),
    CMD_SHOW_INFO("cmd.show.info", "&6Power / Amount of provinces: &v1&v2 / &v3"),
    CMD_SHOW_INVITATION("cmd.show.invitation", "&6Invitation required: "),
    CMD_SHOW_LEADER("cmd.show.leader", "&6Leader: "),
    CMD_SHOW_MEMBERS("cmd.show.members", "&6Members: "),
    CMD_SHOW_RELATIONS("cmd.show.relations", "&6Relations: "),
    CMD_SHOW_STABILITY("cmd.show.stability", "&6Stability: "),
    CMD_SHOW_STABILITY_MOD_BASE("cmd.show.stabilityMod.base", "Base: "),
    CMD_SHOW_STABILITY_MOD_EXHAUSTION("cmd.show.stabilityMod.exhaustion", "War exhaustion: "),
    CMD_SHOW_STABILITY_MOD_PROVINCES("cmd.show.stabilityMod.provinces", "Provinces: "),
    CMD_SHOW_STABILITY_MOD_ABSENT_MONARCH("cmd.show.stabilityMod.absentMonarch", "Absent monarch: "),
    CMD_SHOW_STABILITY_MOD_POWER("cmd.show.stabilityMod.power", "Power: "),
    CMD_SHOW_STABILITY_MOD_WEALTH("cmd.show.stabilityMod.wealth", "Wealth: "),
    CMD_SHOW_TAG("cmd.show.tag", "&6Tag: "),
    CMD_TAG_SUCCESS("cmd.tag.success", "&aThe faction &v1 &achanged their tag to &6&v2&a."),
    CMD_TITLE_SUCCESS("cmd.title.success", "&v1 &achanged the title of &v2 &ato &6&v3&a."),
    CMD_UNCLAIM_FAIL("cmd.unclaim.fail", "&4You cannot unclaim your capital province."),
    CMD_UNCLAIM_SUCCESS("cmd.unclaim.success", "&aSuccessfully unclaimed the region &v1&a."),
    CMD_UNINVITE_SUCCESS("cmd.uninvite.success", "&v1 &aremoved &v2&a's invitation to join your faction."),
    CMD_WAR_STATUS_ATTACKERS("cmd.warStatus.attackers", "&4Attackers: &a"),
    CMD_WAR_STATUS_CASUS_BELLI("cmd.warStatus.casusBelli", "&4Casus Belli: &a"),
    CMD_WAR_STATUS_DATE("cmd.warStatus.date", "&4Date: &a"),
    CMD_WAR_STATUS_DEATHS("cmd.warStatus.deaths", "&4Deaths: &a"),
    CMD_WAR_STATUS_DEFENDERS("cmd.warStatus.deFfenders", "&4Defenders: &a"),
    CMD_WAR_STATUS_HEADLINE("cmd.warStatus.headline", "&aATTACKER &2| &aDEFENDER &2| &aCASUS BELLI &2| &aSTART DATE"),
    CMD_WAR_STATUS_KD("cmd.warStatus.kd", "&4K/D: &a"),
    CMD_WAR_STATUS_KILLS_AND_DEATHS("cmd.warStatus.killsAndDeaths", " &4Kills/Deaths: &a&v1&4/&a&v2&4 => &a&v3"),
    CMD_WAR_STATUS_NO_WARS("cmd.warStatus.noWars", "&aThe faction &v1 &ais currently not at war."),
    CMD_WAR_STATUS_POINTS("cmd.warStatus.points", " &4Points: &a"),
    CMD_WORLD_AUTOCLAIM_END("cmd.world.autoclaim.end", "&aYou are not adding chunks to the region any longer."),
    CMD_WORLD_AUTOCLAIM_START("cmd.world.autoclaim.start", "&aYou are now autocmatically adding chunks to the region &v1&a while moving."),
    CMD_WORLD_CHUNK_ADDED("cmd.world.chunkAdded", "&aSuccessfully added this chunk to the region &v1&a."),
    CMD_WORLD_CHUNK_REMOVED("cmd.world.chunkRemoved", "&aSuccessfully removed this chunk from the region &v1&a."),
    CMD_WORLD_CREATE("cmd.world.create", "&aSuccessfully created a new region named &v1&a."),
    CMD_WORLD_DELETE("cmd.world.delete", "&aSuccessfully deleted the region &v1&a."),
    CMD_WORLD_LEVEL("cmd.world.level", "&aSuccessfully changed the level of the region &v1&a to &6&v2&a."),
    CMD_WORLD_RENAMED("cmd.world.renamed", "&aSuccessfully renamed the region &v1&a to &v2&a."),
    CMD_WORLD_TYPE("cmd.world.type", "&aSuccessfully changed the type of the region &v1&a to &6&v2&a."),
    DEATH_DEFAULT_DEATH("death.default.killed", "&4You died and lost &6&v1 &4power points. Your power is now &6&v2&4."),
    DEATH_PLAYER_KILL_KILLED("death.playerKill.killed", "&4You have been killed by &v1 &4and lost &6&v2&4 power points. Your power is now &6&v3&4."),
    DEATH_PLAYER_KILL_KILLER("death.playerKill.killer", "&aYou have killed &v1 &aand won &6&v2&a power points. Your power is now &6&v3&a."),
    ERROR_ALLOD("error.allod", "&v1 &4is an allod."),
    ERROR_CANNOT_ATTACK_ALLIED_FACTION("error.cannotAttackAlliedFaction", "&4You cannot attack an allied faction."),
    ERROR_CANNOT_PASS_CAPITAL("cmd.cannotPass.capital", "&4You cannot give your capital to a vassal."),
    ERROR_CANNOT_PASS_LAND("cmd.cannotPass.land", "&4You cannot give this land away."),
    ERROR_CANNOT_TRADE_WITH_ITSELF("error.cannotTradeWithItself", "&4A faction cannot trade with itself."),
    ERROR_CAPITAL_MOVE_COOLDOWN("error.capitalMoveCooldown", "&4You must wait until &6&v1 &4to move your capital."),
    ERROR_CMD_NOT_EXIST_1("error.cmdNotExist.1", "&4Command &6&v1&4 does not exist."),
    ERROR_CMD_NOT_EXIST_2("error.cmdNotExist.2", "&4Please enter &6/f help&4 for help."),
    ERROR_DO_NOT_MOVE("error.doNotMove", "&4You must not move."),
    ERROR_ECON_DISABLED("error.econDisabled", "&4Economy features are disabled."),
    ERROR_HOME_NOT_IN_ALLIED_TERRITORY("error.homeNotInAlliedTerritory", "&4A player home must be in allied territory."),
    ERROR_IN_WAR("error.inWar", "&4You are in war with &v1&4."),
    ERROR_JOIN_FACTION("error.joinFaction", "&4You have to join a faction in order to do this."),
    ERROR_LAND_NO_CORE("error.langNoCore", "&4This land is not a core province of your faction."),
    ERROR_LAND_NOT_FOR_SALE("error.land.notForSale", "&4This land is not for sale."),
    ERROR_LAND_WILDERNESS("error.land.wilderness", "&4You cannot do this in the wilderness."),
    ERROR_LEAVE_FACTION("error.leaveFaction", "&4You have to leave your faction in order to do this."),
    ERROR_MAX_IDEA_GROUPS_REACHED("error.maxIdeaGroupsReached", "&7You reached the maximum amount of idea groups."),
    ERROR_NAME_IN_USE("error.nameInUse", "&4The name &6&v1 &4is already in use."),
    ERROR_NO_PERMISSION("error.noPermission", "&4You do not have permission to do this."),
    ERROR_NO_SUCH_CASUS_BELLI("error.noSuch.casusBelli", "&4The casus belli &6&v1 &4does not exist."),
    ERROR_NO_SUCH_FACTION("error.noSuch.faction", "&4The faction &6&v1 &4does not exist."),
    ERROR_NO_SUCH_GOVERNMENT_TYPE("error.noSuch.governmentType", "&4The government type &6&v1 &4does not exist."),
    ERROR_NO_SUCH_PLAYER("error.noSuch.player", "&4The player &6&v1 &4does not exist."),
    ERROR_NO_SUCH_REGION("error.noSuch.region", "&4This region does not exist."),
    ERROR_NO_SUCH_REGION_TYPE("error.noSuch.regionType", "&4This region type does not exist."),
    ERROR_NO_SUCH_RELATION("error.noSuch.relation", "&4The relation &6&v1 &4does not exist."),
    ERROR_NOT_ENOUGH_MONEY("error.notEnoughMoney", "&4You cannot afford &6&v1 &4to do this."),
    ERROR_NOT_ENOUGH_MONEY_FACTION("error.notEnoughMoneyFaction", "&4The faction &v1 &4cannot afford &6&v2 &4to do this."),
    ERROR_NOT_NUMERIC("error.notNumeric", "&6&v1 &4is not a numeric value."),
    ERROR_NOT_VASSAL("error.notVassal", "&v1 &4is not a vassal of &v2&4."),
    ERROR_NOT_WILDERNESS("error.notWilderness", "&4You can only do this in the wilderness."),
    ERROR_OWN_FACTION("error.ownFaction", "&4This is your own faction."),
    ERROR_PERSONAL_UNION_WITH_FACTION("error.personalUnionWithFaction", "&4The faction &v1 &4has a personal union with &v2&4."),
    ERROR_PERSONAL_UNION_WITH_FACTION_REQUIRED("error.personalUnionWithFaction", "&4The faction &v1 &4does not have a personal union with &v2&4."),
    ERROR_PLAYER_NOT_IN_ANY_FACTION("error.notInAnyFaction", "&4The player &6&v1 &4is not member of a faction."),
    ERROR_PLAYER_NOT_IN_FACTION("error.playerNotInFaction", "&4The player &6&v1 &4is not member of the faction &6&v2&4."),
    ERROR_PLAYER_NOT_ONLINE("error.playerNotOnline", "&4The player &6&v1 &4is not online."),
    ERROR_REGION_IS_ALREADY_CLAIMED("error.regionIsAlreadyClaimed", "&v1 &4is already claimed by &v2&4."),
    ERROR_REGION_IS_CORE("error.regionIsCore", "&v1 &4is a core province of &v2&4."),
    ERROR_SELECT_IDEA_GROUP("error.selectIdeaGroup", "&7You have to select the idea group first."),
    ERROR_SPECIFY_PLAYER("error.specifyFaction", "&4You have to specify a player."),
    ERROR_SPECIFY_FACTION("error.specifyFaction", "&4You have to specify a faction."),
    ERROR_VASSAL("error.vassal", "&4The faction &v1 &4is a vassal."),
    ERROR_VASSAL_IS_MOTHER_ADMIN("error.vassalIsMotherAdmin", "&4The player &v1 &4is already leader of the mother faction."),
    FACTION_INTEGRATED_VASSAL("faction.integratedVassal", "&aThe faction &v1 &aintegrated their vassal &v2&a."),
    FACTION_INVITE("faction.invite", "&aThe faction &v1&a would like to have you as a comrade. Join them?"),
    FACTION_JOIN_ACCEPT("faction.join.accept", "&v1 &ajoined the faction."),
    FACTION_JOIN_DENY("faction.join.deny", "&v1 &adecided not to join the faction."),
    FACTION_LEFT("faction.left", "&v1 &aleft the faction."),
    FACTION_LOST_CLAIM("faction.lostClaim", "&aThe faction &v1&a lost their claim for &v2&a."),
    FACTION_LOST_CORE("faction.lostCore", "&aThe faction &v1&a lost their core at &v2&a."),
    FACTION_NEW_CLAIM("faction.newClaim", "&aThe faction &v1&a got a new claim for &v2&a."),
    FACTION_NEW_CORE("faction.newCore", "&aThe faction &v1&a got a new core at &v2&a."),
    FACTION_PAID("faction.paid", "&aThe faction &v1 &apaid &6&v2&a."),
    FACTION_PLAYER_KICKED("faction.playerKicked", "&aThe player &v1 &ahas been kicked out of the faction by &v2&a."),
    FACTION_PLAYER_KICKED_AUTO("faction.playerKickedAuto", "&aThe player &v1 &ahas been kicked out of the faction automatically."),
    FACTION_PERSONAL_UNION_FORMED("faction.personalUnionFormed",
            "&aThe factions &v1 &aand &v2 &adecided to unite their dynasties under &v3 &aand formed a personal union."),
    FACTION_STORAGE("faction.storage", "&aStorage"),
    GOVERNMENT_TYPE_MONARCHY("governmentType.monarchy", "Monarchy"),
    GOVERNMENT_TYPE_REPUBLIC("governmentType.republic", "Republic"),
    GOVERNMENT_TYPE_THEOCRACY("governmentType.theocracy", "Theocracy"),
    HELP_ADD_CASUS_BELLI("help.addCasusBelli", "/f addCasusBelli [subject faction] [CB type] [target faction] - Adds a CB to the faction."),
    HELP_ADMIN("help.admin", "/f admin ([faction]) [player] - Passes the ownership of a faction to another player."),
    HELP_ALLY("help.ally", "/f ally ([faction]) [target] - Sends an alliance request to the target faction."),
    HELP_CASUS_BELLI("help.casusBelli", "/f casusBelli ([faction] - Shows all of your casus belli (except raid)."),
    HELP_CHAT("help.chat", "/f chat [f(action)|p(ublic)] [faction] - Changes the chat mode."),
    HELP_CLAIM("help.claim", "/f claim ([faction]) - Claims a territory."),
    HELP_CONFIRM_WAR("help.confirmWar", "/f confirmWar [date] - Technical command used to confirm wars."),
    HELP_CREATE("help.create", "/f create [tag] - Creates a new faction."),
    HELP_CREATE_BULL("help.create.bull", "/f createBull [name] - Creates a new bull with [name] as the author."),
    HELP_CREATE_VASSAL("help.createVassal", "/f createVassal [tag] [leader] - Creates a new faction as your vassal."),
    HELP_DESC("help.desc", "/f desc [faction] [description] - Changes the description of the faction."),
    HELP_DISBAND("help.disband", "/f disband [faction] - Disbands a faction."),
    HELP_GIVE_REGION("help.giveRegion", "/f giveRegion [faction] - Gives the current region to a vassal. Removes cores."),
    HELP_HELP("help.help", "/f help [page] - Shows the help page."),
    HELP_HOME("help.home", "/f home ([faction]) - Teleports to the home point of a faction."),
    HELP_IDEA("help.idea", "/f idea ([faction]) - Opens the idea menu."),
    HELP_INTEGRATE("help.integrate", "/f integrate ([faction]) [vassal] - Integrates a vassal."),
    HELP_INVITE("help.invite", "/f invite [faction] [player] - Invites a player to join the faction."),
    HELP_JOIN("help.join", "/f join [faction] - Accepts an invitation."),
    HELP_KICK("help.kick", "/f kick [player] - Kicks the specified player out of the faction."),
    HELP_LEAVE("help.leave", "/f leave - Makes the player leave the faction."),
    HELP_LIST("help.list", "/f list ([disbanded]) - Shows a list of all factions."),
    HELP_LONG_TAG("help.longTag", "/f longtag [faction] [tag] - Changes the full name of a faction."),
    HELP_MAIN("help.main", "/f - General status information."),
    HELP_MOB("help.mob", "/f mob [type] - Spawns a faction mob of this type."),
    HELP_MOD("help.mod", "/f mod [faction] [player] - Grants another player faction moderator permissions."),
    HELP_MONEY("help.money", "/f money [faction] [b(alance)|d(eposit)|w(ithdraw)] ([amount])"),
    HELP_NEUTRAL("help.neutral", "/f neutral ([faction]) [target] - Changes the relation with a faction to neutral."),
    HELP_OATH("help.oath", "/f oath ([faction]) [target] - Offers an oath of fealty to the faction sothat you become its vassal."),
    HELP_OPEN("help.open", "/f open [faction] - Allows / Forbids all players to join the faction without an invitation."),
    HELP_PAYDAY("help.payday", "/f payday ([amount]) - Enforces paydays."),
    HELP_PLAYER_HOME("help.playerHome", "/home ([player]) - Teleports the sender to the player's home."),
    HELP_POWER("help.power", "/f power ([player]) - Displays a player's power value."),
    HELP_REGION("help.region", "/f region ([region name/ID]) - Shows information about a region."),
    HELP_REGIONS("help.regions", "/f regions - Shows a list of all regions."),
    HELP_RELATION("help.relation", "/f relation [faction] [target] [relation] - Sends a relation request to the target faction."),
    HELP_RELOAD("help.reload", "/f reload - Reloads the plugin."),
    HELP_SCOREBOARD("help.scoreboard", "/f scoreboard - Toggles the scoreboard."),
    HELP_SET_ANTHEM("help.setAnthem", "/f setAnthem [faction] [anthem name] - Sets the faction anthem to a custom sound."),
    HELP_SET_BANNER("help.setBanner", "/f setBanner [faction] - Sets the faction banner to the one in the player's main hand."),
    HELP_SET_CAPITAL("help.setCapital", "/f setCapital - Sets the faction's capital to the player's current region."),
    HELP_SET_COLOR("help.setColor", "/f setColor [faction] [fill color] [line color] [icon] - Sets the livemap color to a specific RRGGBB color."),
    HELP_SET_GOVERNMENT("help.setGovernment", "/f setGovernment [faction] [type] - Sets the government type of the faction."),
    HELP_SET_HOME("help.setHome", "/f setHome [faction] - Sets the home point of the faction to the current position."),
    HELP_SET_PLAYER_HOME("help.setPlayerHome", "/sethome ([player]) - Sets a player's home location."),
    HELP_SET_POWER("help.setPower", "/f setPower [player] [value] - Sets a player's power to a specific value."),
    HELP_SHORT_TAG("help.shortTag", "/f shortTag ([faction]) [tag] - Changes the short tag of the faction."),
    HELP_SHOW("help.show", "/f show [faction] - Shows a faction's status information."),
    HELP_STORAGE("help.storage", "/f storage [faction] - Shows a faction's storage."),
    HELP_TAG("help.tag", "/f tag ([faction]) [tag] - Changes the name of the faction."),
    HELP_TITLE("help.title", "/f title [player] [title] - Changes the player's title."),
    HELP_TRADE_OFFER("help.tradeOffer", "/f tradeOffer ([faction]) - Creates a trade offer."),
    HELP_UNCLAIM("help.unclaim", "/f unclaim - Unclaims a territory."),
    HELP_UNINVITE("help.uninvite", "/f uninvite ([faction]) [player] - Removes a player's invitation."),
    HELP_UNITE("help.unite", "/f unite ([faction]) [target] - Forms a real union with another faction."),
    HELP_VASSALIZE("help.vassalize", "/f vassalize ([faction]) [target] - Vassalizes the target faction."),
    HELP_WAR("help.war", "/f war [faction] - Declares war on a faction."),
    HELP_WAR_STATUS("help.warStatus", "/f warStatus ([faction]) - Shows the war status of a faction."),
    HELP_WORLD("help.world", "/f world - World management commands for server admins."),
    IDEA_GROUP_CENTRALIZATION("idea.group.centralization", "Centralization"),
    IDEA_GROUP_DIPLOMACY("idea.group.diplomacy", "Diplomacy"),
    IDEA_GROUP_ECONOMY("idea.group.economy", "Economy"),
    IDEA_GROUP_MERCENARY("idea.group.mercenary", "Mercenary"),
    IDEA_GROUP_RELIGION("idea.group.religion", "Religion"),
    IDEA_GROUP_SETTLER("idea.group.settler", "Settler"),
    IDEA_GROUP_TRADE("idea.group.trade", "Trade"),
    IDEA_DESC_SETTLER_COLONIZATION("idea.desc.settler.colonization", "&3+10% Manpower"),
    IDEA_MENU_GROUPS_TITLE("idea.menu.groups.title", "&6&lIdea Groups"),
    IDEA_MENU_GROUPS_DESELECTED("idea.menu.groups.deselected", "&aYou deselected the idea group &6&v1&a."),
    IDEA_MENU_GROUPS_SELECTED("idea.menu.groups.selected", "&aYou selected the idea group &6&v1&a."),
    IDEA_MENU_IDEAS_TITLE("idea.menu.ideas.title", "&6&l&v1 Ideas"),
    IDEA_NAME_SETTLER_COLONIZATION("idea.name.settler.colonization", "Colonization"),
    LOG_DYNMAP_NOT_ENABLED("log.dynmapNotEnabled", "&4Could not find Dynmap."),
    LOG_NEW_FACTION_DATA("log.newFactionData", "&6A new faction data file has been created and saved as &v1."),
    LOG_NEW_PLAYER_DATA("log.newPlayerData", "&6A new player data file has been created and saved as &v1."),
    MISC_ACCEPT("misc.accept", "[ ACCEPT ]"),
    MISC_CANCEL("misc.cancel", "[ CANCEL ]"),
    MISC_CONTINUE("misc.continue", "&6&lCONTINUE"),
    MISC_DENY("misc.deny", "[ DENY ]"),
    MISC_LONER("misc.loner", "Loner"),
    MISC_PURCHASE_FAIL("misc.purchase.success", "&4You cannot afford &6&v1&4."),
    MISC_PURCHASE_SUCCESS("misc.purchase.success", "&aYou successfully purchased &6&v1&a."),
    MISC_SHIFT_CLICK_PURCHASE("misc.shiftClick.purchase", "&7Hold [SHIFT] and click to purchase."),
    MISC_SHIFT_CLICK_SELECT("misc.shiftClick.select", "&7Hold [SHIFT] and click to select."),
    MISC_WILDERNESS("misc.wilderness", "Wilderness"),
    MOB_TRADER("mob.trader", "&6Trader"),
    MOB_VILLAGER("mob.villager", "&6Villager"),
    POPULATION_ADJUST_CONSUME("population.adjustConsume", "&6&lAdjust consume - &v1"),
    POPULATION_DEMANDS_BUTTON("population.demands.button", "&aDemands"),
    POPULATION_DEMANDS_TITLE("population.demands.title", "&6&lDemands - &v1"),
    POPULATION_DENY_RESOURCE("population.denyResource", "&4Deny one"),
    POPULATION_GRANT_RESOURCE("population.grantResource", "&aGrant one"),
    POPULATION_GRANTING1("population.granting1", "&aThe people are currently granted"),
    POPULATION_GRANTING2("population.granting2", "&6&v1 &aunits of &6&v2&a."),
    POPULATION_MILITARY_BUTTON("population.military.button", "&aMilitary Status"),
    POPULATION_MILITARY_SOLDIERS("population.military.soldiers", "&aSoldiers"),
    POPULATION_MILITARY_TITLE("population.military.title", "&6&lMilitary Status - &v1"),
    POPULATION_REQUIRED("population.required", "&6&v1 &apeople need &6&v2 &aunits of &6&v3&a."),
    POPULATION_TITLE("population.title", "&6&lPopluation - &v1"),
    POPULATION_WARNING_NOT_ENOUGH_RESOURCES_GRANTED("population.warning.notEnoughResourcesGranted",
            "&4Your faction does not grant as many resources of the following types as your people wish:"),
    POPULATION_WARNING_TOO_MANY_RESOURCES_GRANTED("population.warning.tooManyResourcesGranted",
            "&4Your faction grants more resources of the following types than your people need:"),
    PROTECTION_CANNOT_ATTACK_CAPITAL("protection.cannotAttack.capital", "&4You may not attack in the capital of &v1&4."),
    PROTECTION_CANNOT_ATTACK_FACTION("protection.cannotAttack.faction", "&4You may not attack in the territory of &v1&4."),
    PROTECTION_CANNOT_ATTACK_PLAYER("protection.cannotAttack.player", "&4You may not attack a member of &v1&4."),
    PROTECTION_CANNOT_BUILD_FACTION("protection.cannotBuildFaction", "&4You may not build in the territory of &v1&4."),
    PROTECTION_CANNOT_BUILD_WILDERNESS("protection.cannotBuildWilderness", "&4You may not build in the wilderness."),
    PROTECTION_CANNOT_DESTROY_FACTION("protection.cannotDestroyFaction", "&4You may not destroy the territory of &v1&4."),
    PROTECTION_CANNOT_DESTROY_WILDERNESS("protection.cannotDestroyWilderness", "&4You may not destroy the wilderness."),
    PROTECTION_CANNOT_EQUIP_FACTION("protection.cannotEquipFaction", "&4You may not equip armor stands in the territory of &v1&4."),
    PROTECTION_CANNOT_INTERACT_FACTION("protection.cannotInteractFaction", "&4You may not interact with &6&v1 &4in the territory of &v2&4."),
    PROTECTION_CANNOT_LEASH_FACTION("protection.cannotLeashFaction", "&4You may not leash animals in the territory of &v1&4."),
    PROTECTION_CANNOT_SHEAR_FACTION("protection.cannotShearFaction", "&4You may not sheer animals in the territory of &v1&4."),
    PROTECTION_CANNOT_SPLASH_POTION_FACTION("protection.cannotSplashPotionFaction", "&4You may not splash potions in the territory of &v1&4."),
    PROTECTION_CANNOT_TAME_FACTION("protection.cannotTameFaction", "&4You may not tame animals in the territory of &v1&4."),
    PROTECTION_CANNOT_UNLEASH_FACTION("protection.cannotLeashFaction", "&4You may not unleash animals in the territory of &v1&4."),
    PROTECTION_CANNOT_REGISTER_FACTION("protection.cannotRegisterFaction", "&4You may not register LWC protections in the territory of &v1&4."),
    PROTECTION_DAMAGE_REDUCED("protection.damageReduced", "&4Your damage is reduced by &v1% in the territory of &v2&4!"),
    REGION_BARREN("region.barren", "Barren"),
    REGION_CITY("region.city", "City"),
    REGION_DESERT("region.desert", "Desert"),
    REGION_FARMLAND("region.farmland", "Farmland"),
    REGION_FOREST("region.forest", "Forest"),
    REGION_MAGIC("region.magic", "Magic"),
    REGION_MOUNTAINOUS("region.mountainous", "Mountainous"),
    REGION_SEA("region.sea", "Sea"),
    REGION_WAR_ZONE("region.warZone", "War Zone"),
    RELATION_ALLIANCE("relation.alliance", "Alliance"),
    RELATION_ALLIANCE_DESC("relation.allianceDesc", "Two friendly factions form an alliance to defend each other."),
    RELATION_COALITION("relation.coalition", "Coalition"),
    RELATION_COALITION_DESC("relation.coalitionDesc", "Two neutral factions form a transient alliance to defeat a common enemy."),
    RELATION_CONFIRMED("relation.confirmed", "&aThe factions &v1 &aand &v2 &aset their relation to &v3&a."),
    RELATION_DENIED("relation.denied", "&aThe faction &v1 &adenied your request to set your relation to &v2&a."),
    RELATION_ENEMY("relation.enemy", "Enemy"),
    RELATION_ENEMY_DESC("relation.enemyDesc", "It seems these factions don't like each other very much..."),
    RELATION_LORD("relation.lord", "Lord"),
    RELATION_LORD_DESC("relation.lordDesc", "This faction rules over its vassal."),
    RELATION_OWN("relation.own", "Own"),
    RELATION_OWN_DESC("relation.ownDesc", "Your faction."),
    RELATION_PEACE("relation.peace", "Peace"),
    RELATION_PEACE_DESC("relation.peaceDesc", "There are no special contacts to this faction."),
    RELATION_PERSONAL_UNION("relation.personalUnion", "Personal Union"),
    RELATION_PERSONAL_UNION_DESC("relation.personalUnionDesc", "Two factions are ruled by the same monarch."),
    RELATION_REAL_UNION("relation.realUnion", "Real Union"),
    RELATION_REAL_UNION_DESC("relation.realUnionDesc", "An advanced personal union. The factions can be regarded as one."),
    RELATION_UNITED("relation.united", "&aThe factions &v1 &aand &v2 &aformed a &2Real Union&a."),
    RELATION_VASSAL("relation.vassal", "Vassal"),
    RELATION_VASSAL_DESC("relation.vassalDesc", "This faction vowed to serve its foreign lord."),
    RELATION_VASSALIZED("relation.vassalized", "&aThe faction &v1 &avassalized &v2&a."),
    RELATION_WISH("relation.wish", "&aThe faction &v1 &aasked your faction to change your relation to &v2&a."),
    RELATION_WISH_OWN("relation.wishOwn", "&v1 &aasked the faction &v2 &ato change your relation to &v3&a."),
    RESOURCE_COAL("resource.coal", "Coal"),
    RESOURCE_SULPHUR("resource.sulphur", "Sulphur"),
    RESOURCE_GOLD("resource.gold", "Gold"),
    RESOURCE_IRON("resource.iron", "Iron"),
    RESOURCE_DIAMOND("resource.diamond", "Diamond"),
    RESOURCE_EMERALD("resource.emerald", "Emerald"),
    RESOURCE_LAPIS_LAZULI("resource.lapisLazuli", "Lapis Lazuli"),
    RESOURCE_QUARTZ("resource.quartz", "Quartz"),
    RESOURCE_REDSTONE("resource.redstone", "Redstone"),
    RESOURCE_ANDESITE("resource.andesite", "Andesite"),
    RESOURCE_DIORITE("resource.diorite", "Diorite"),
    RESOURCE_GRANITE("resource.granite", "Granite"),
    RESOURCE_GRAVEL("resource.gravel", "Gravel"),
    RESOURCE_OBSIDIAN("resource.obsidian", "Obsidian"),
    RESOURCE_STONE("resource.stone", "Stone"),
    RESOURCE_CHICKEN("resource.chicken", "Chicken"),
    RESOURCE_COW("resource.cow", "Cow"),
    RESOURCE_HORSE("resource.horse", "Horse"),
    RESOURCE_PIG("resource.pig", "Pig"),
    RESOURCE_RABBIT("resource.rabbit", "Rabbit"),
    RESOURCE_SHEEP("resource.sheep", "Sheep"),
    RESOURCE_APPLE("resource.apple", "Apple"),
    RESOURCE_BEETROOT("resource.beetroot", "Beetroot"),
    RESOURCE_CARROT("resource.carrot", "Carrot"),
    RESOURCE_CHORUS("resource.chorus", "Chorus"),
    RESOURCE_COCOA("resource.cocoa", "Cocoa"),
    RESOURCE_MELON("resource.melon", "Melon"),
    RESOURCE_POTATO("resource.potato", "Potato"),
    RESOURCE_PUMPKIN("resource.pumpkin", "Pumpkin"),
    RESOURCE_SUGAR("resource.sugar", "Sugar"),
    RESOURCE_WHEAT("resource.wheat", "Wheat"),
    RESOURCE_ACACIA("resource.acacia", "Acacia Wood"),
    RESOURCE_BIRCH("resource.birch", "Birch Wood"),
    RESOURCE_DARK_OAK("resource.darkOak", "Dark Oak Wood"),
    RESOURCE_JUNGLE("resource.jungle", "Jungle Wood"),
    RESOURCE_OAK("resource.oak", "Oak Wood"),
    RESOURCE_SPRUCE("resource.spruce", "Spruce Wood"),
    RESOURCE_PAPER("resource.paper", "Paper"),
    RESOURCE_MUSHROOMS("resource.mushrooms", "Mushrooms"),
    RESOURCE_CODFISH("resource.codfish", "Codfish"),
    RESOURCE_CLOWNFISH("resource.clownfish", "Clownfish"),
    RESOURCE_PUFFERFISH("resource.pufferfish", "Pufferfish"),
    RESOURCE_SALMON("resource.salmon", "Salmon"),
    RESOURCE_INK("resource.ink", "Ink"),
    RESOURCE_SALT("resource.salt", "Salt"),
    RESOURCE_WATER("resource.water", "Water"),
    RESOURCE_CLAY("resource.clay", "Clay"),
    RESOURCE_PRISMARINE("resource.prismarine", "Prismarine"),
    RESOURCE_DRAGON_BREATH("resource.dragonBreath", "Dragon Breath"),
    RESOURCE_EXPERIENCE("resource.experience", "Experience"),
    RESOURCE_NETHER_WART("resource.netherWart", "Nether Wart"),
    RESOURCE_PURPUR("resource.purpur", "Purpur"),
    RESOURCE_CACTUS("resource.cactus", "Cactus"),
    RESOURCE_GLASS("resource.glass", "Glass"),
    RESOURCE_RED_SANDSTONE("resource.redSandstone", "Red Sandstone"),
    RESOURCE_YELLOW_SANDSTONE("resource.yellowSandstone", "Yellow Sandstone"),
    RESOURCE_CRAFT("resource.craft", "Craft"),
    RESOURCE_MANPOWER("resource.manpower", "Manpower"),
    RESOURCE_TAXES("resource.taxes", "Taxes"),
    RESOURCE_SUBCATEGORY_ALCHEMY("resource.subcategory.alchemy", "Alchemy"),
    RESOURCE_SUBCATEGORY_CANNONING("resource.subcategory.cannoning", "Cannoning"),
    RESOURCE_SUBCATEGORY_DYE("resource.subcategory.dye", "Dye"),
    RESOURCE_SUBCATEGORY_FUR("resource.subcategory.fur", "Fur"),
    RESOURCE_SUBCATEGORY_GLASS("resource.subcategory.glass", "Glass"),
    RESOURCE_SUBCATEGORY_HEATING("resource.subcategory.heating", "Heating"),
    RESOURCE_SUBCATEGORY_JEWELRY("resource.subcategory.jewelry", "Jewelry"),
    RESOURCE_SUBCATEGORY_LEATHER("resource.subcategory.leather", "Leather"),
    RESOURCE_SUBCATEGORY_LITERATURE("resource.subcategory.literature", "Literature"),
    RESOURCE_SUBCATEGORY_MEAT("resource.subcategory.meat", "Luxury food"),
    RESOURCE_SUBCATEGORY_RIDERS("resource.subcategory.riders", "Riders"),
    RESOURCE_SUBCATEGORY_ROADS("resource.subcategory.roads", "Roads"),
    RESOURCE_SUBCATEGORY_SMITHERY("resource.subcategory.smithery", "Smithery"),
    RESOURCE_SUBCATEGORY_SPICES("resource.subcategory.spices", "Spices"),
    RESOURCE_SUBCATEGORY_STAPLES("resource.subcategory.staples", "Staples"),
    RESOURCE_SUBCATEGORY_STONE("resource.subcategory.stone", "Stone"),
    RESOURCE_SUBCATEGORY_WATER("resource.subcategory.water", "Water"),
    RESOURCE_SUBCATEGORY_WOOD("resource.subcategory.wood", "Wood"),
    SATURATION_LEVEL_FULLY_SATURATED("saturationLevel.fullySaturated", "Fully saturated"),
    SATURATION_LEVEL_MOSTLY_SATURATED("saturationLevel.mostlySaturated", "Mostly saturated"),
    SATURATION_LEVEL_NOT_SATURATED("saturationLevel.notSaturated", "Not saturated"),
    SATURATION_LEVEL_PARTIALLY_SATURATED("saturationLevel.partiallySaturated", "Partially saturated"),
    SATURATION_LEVEL_POOR("saturationLevel.poor", "Poor"),
    SATURATION_LEVEL_SATURATED("saturationLevel.saturated", "Saturated"),
    SATURATION_LEVEL_SURPLUS("saturationLevel.surplus", "Surplus"),
    STORAGE_NON_PHYSICAL_MANPOWER("storage.nonPhysical.manpower", "&cCheck your villagers to see information."),
    STORAGE_NON_PHYSICAL_TAXES("storage.nonPhysical.taxes", "&cTaxes flow into your bank account (/f money)."),
    STORAGE_PAYDAY("storage.payday", "&aA day has passed. Taxes and trade have been collected."),
    STORAGE_NON_PHYSICAL_WARNING("storage.nonPhysical.warning", "&c&v1 is a non-physical resource."),
    STORAGE_STOCK("storage.stock", "&3Stock: &v1"),
    STORAGE_TITLE("storage.title", "&6&lStorage - &v1"),
    TRADE_CONSUME("trade.consume", "&4Consume: &v1"),
    TRADE_ECONOMY("trade.economy", "&6&lEconomy - &v1"),
    TRADE_EXPORT("trade.export", "&4Export"),
    TRADE_IMPORT("trade.import", "&aImport"),
    TRADE_INCOME_MANAGEMENT("trade.incomeManagement", "&aIncome Management"),
    TRADE_PRICE("trade.price", "Price"),
    TRADE_OFFER_CHOOSE_EXPORT("trade.offer.chooseExport", "&2&lChoose your action:"),
    TRADE_OFFER_CHOOSE_PARTNER("trade.offer.choosePartner", "&2&lChoose your trade partner:"),
    TRADE_OFFER_AMOUNT("trade.offer.amount", "Amount"),
    TRADE_OFFER_CHOOSE_RESOURCE("trade.offer.chooseResource", "&2&lChoose a resource:"),
    TRADE_OFFER_SEND_TRADE("trade.offer.send.trade", "&aThe faction &v1 &aoffers us a trade."),
    TRADE_OFFER_SEND_EXPORT("trade.offer.send.export", "&aThey would like to export &6&v1 &afor &6&v2&a."),
    TRADE_OFFER_SEND_IMPORT("trade.offer.send.import", "&aThey would like to import &6&v1 &afor &6&v2&a."),
    TRADE_OFFER_TITLE("trade.offer.title", "&aTrade Offer"),
    TRADE_RESOURCE_TITLE("trade.resourceTitle", "&6&l&v1 - &v2"),
    TRADE_SUCCESS_EXPORT("trade.success.export", "&aYou successfully exported &6&v1 &afor &6&v2 &ato &v3&a."),
    TRADE_SUCCESS_IMPORT("trade.success.import", "&aYou successfully imported &6&v1 &afor &6&v2 &afrom &v3&a."),
    TRADE_TITLE("trade.title", "&6&lTrade - &v1"),
    WAR_CALL_TO_ARMS_ALLY_1("war.callToArms.ally.1", "&dYou are allied to &v1."),
    WAR_CALL_TO_ARMS_ALLY_2_ALLIED("war.callToArms.ally.2.allied", "&4They are allied to your enemy. Your alliance"),
    WAR_CALL_TO_ARMS_ALLY_3_ALLIED("war.callToArms.ally.3.allied", "&4will break if you declare war."),
    WAR_CALL_TO_ARMS_ALLY_2_NOT_ALLIED("war.callToArms.ally.2.notAllied", "&eYou may ask, but not force them"),
    WAR_CALL_TO_ARMS_ALLY_3_NOT_ALLIED("war.callToArms.ally.3.notAllied", "&eto join an offensive war."),
    WAR_CALL_TO_ARMS_COALITION_1("war.callToArms.coalition.1", "&5You've prepared a coalition with &v1."),
    WAR_CALL_TO_ARMS_COALITION_2("war.callToArms.coalition.2", "&2They already agreed to side with you."),
    WAR_CALL_TO_ARMS_OWN("war.callToArms.own", "&a&v1 is your faction."),
    WAR_CALL_TO_ARMS_VASSAL_1("war.callToArms.vassal.1", "&bv1 is your vassal."),
    WAR_CALL_TO_ARMS_VASSAL_2_STRONGER("war.callToArms.vassal.2.stronger", "&2You are strong enough to enforce their help."),
    WAR_CALL_TO_ARMS_VASSAL_2_WEAKER("war.callToArms.vassal.2.weaker", "&eYou are not strong enough to enforce their help."),
    WAR_CALL_TO_ARMS_DEFENDER("war.callToArms.defender", "&4&v1 will side with your enemy."),
    WAR_CALL_TO_ARMS_ADD("war.callToArms.add", "&6&lClick to call them to arms."),
    WAR_CALL_TO_ARMS_REMOVE("war.callToArms.remove", "&6&lClick to retract the call to arms."),
    WAR_CALL_TO_ARMS_TITLE("war.callToArms.title", "&4&lCall to arms"),
    WAR_DECLARATION_ALLIES("war.declaration.allies", "&9Allies: "),
    WAR_DECLARATION_BROADCAST("war.declaration.broadcast", "&v1 &4of &v2 &4declared war on &v3&4!"),
    WAR_DECLARATION_CANCELLED("war.declaration.cancelled", "&6War cancelled."),
    WAR_DECLARATION_CASUS_BELLI("war.declaration.casusBelli", "&eCasus Belli: "),
    WAR_DECLARATION_DEFENDERS("war.declaration.defenders", "&cDefenders: "),
    WAR_DECLARATION_START_DATE("war.declaration.startDate", "&4&oThe war will start in 24 hours."),
    WAR_DECLARATION_TITLE("war.declaration.title", "&4&l#=== D\u00c9CLARATION DE GUERRE ===#"),
    WAR_DEMAND_MENU_ITEM("war.demand.menu.item", "&3Add item demand"),
    WAR_DEMAND_MENU_LIST("war.demand.menu.list", "&aList demands"),
    WAR_DEMAND_MENU_TITLE("war.demand.menu.title", "Create new war demand"),;

    private String identifier;
    private String message;

    FMessage(String identifier, String message) {
        this.identifier = identifier;
        this.message = message;
    }

    /* Getters and setters */
    @Override
    public String getIdentifier() {
        return identifier;
    }

    @Override
    public String getMessage() {
        return ChatColor.translateAlternateColorCodes('&', message);
    }

    @Override
    public String getMessage(String... args) {
        return FactionsXL.getInstance().getMessageConfig().getMessage(this, args);
    }

    @Override
    public void setMessage(String message) {
        this.message = message;
    }

    /* Actions */
    /**
     * Sends the message to the console.
     */
    public void debug() {
        MessageUtil.log(FactionsXL.getInstance(), getMessage());
    }

    /* Statics */
    /**
     * @param identifer
     * the identifer to set
     */
    public static Message getByIdentifier(String identifier) {
        for (Message message : values()) {
            if (message.getIdentifier().equals(identifier)) {
                return message;
            }
        }

        return null;
    }

    /**
     * @return a FileConfiguration containing all messages
     */
    public static FileConfiguration toConfig() {
        FileConfiguration config = new YamlConfiguration();
        for (FMessage message : values()) {
            config.set(message.getIdentifier(), message.message);
        }
        return config;
    }

}
